### ISSUE TITLE
state-management

### ISSUE THREAD

**Issue by jobypthomas** [salihgueler/amplify_grocery_list#1]
Hi,

@salihgueler Thank you for the starter project template. 
I see no state management solutions were used in it. What is your recommendation if you were to make it a production ready app?

Thanks!

**Comment by jobypthomas** [comment]
@salihgueler Please share the schema.graphql as well.

**Comment by salihgueler** [comment]
Hello @joobypthomas! Thank you for creating this issue. I would recommend anything that you find useful. I will create a project with my opinioanated approach though. I will focus on these in 2 weeks and update your issue with more information.

GraphQL is updated on the blog post but I will share it here as well. 
```
type Grocery @model @auth(rules: [{allow: owner}]) {
  id: ID!
  groceryItems: [GroceryItem] @hasMany(indexName: "byGrocery", fields: ["id"])
  title: String
  fileKey: String
  finalizationDate: AWSDate
  totalAmount: Float
}

type GroceryItem @model @auth(rules: [{allow: owner}]) {
  id: ID!
  name: String!
  isBought: Boolean!
  count: Int!
  groceryID: ID! @index(name: "byGrocery")
}
```

**Comment by salihgueler** [comment]
Hello @joobypthomas! Thank you for creating this issue. I would recommend anything that you find useful. I will create a project with my opinioanated approach though. I will focus on these in 2 weeks and update your issue with more information.

GraphQL is updated on the blog post but I will share it here as well. 
```
type Grocery @model @auth(rules: [{allow: owner}]) {
  id: ID!
  groceryItems: [GroceryItem] @hasMany(indexName: "byGrocery", fields: ["id"])
  title: String
  fileKey: String
  finalizationDate: AWSDate
  totalAmount: Float
}

type GroceryItem @model @auth(rules: [{allow: owner}]) {
  id: ID!
  name: String!
  isBought: Boolean!
  count: Int!
  groceryID: ID! @index(name: "byGrocery")
}
```

**Comment by jobypthomas** [comment]
@salihgueler One more feedback. In Finalize Grocery in TODO(11), the update mutation does not seem to happen. I tried the same mechanism directly from AppSync the update mutation silently errors - no error message return. When I added _version in the AppSync it seemed to work. Currently, the code for the project does not seem to care about the _version. Do we need to incorporate _version into the code?

**Comment by jobypthomas** [comment]
@salihgueler Nevermind. I figured it out. It was the conflict resolution. I disabled and it worked like a charm.

**Comment by jobypthomas** [comment]
@salihgueler 
I got the project working locally. Awesome work.
However when I tried to deploy using Amplify hosting based on the direction from one of your medium post:
https://medium.com/flutter-community/hosting-flutter-web-applications-with-amplify-hosting-and-github-actions-d53ba213767

Auth page loads, but when I enter the username and password, it authenticates but redirects to a blank page.
I see the following error in the browser console:
NoSuchMethodError: method not found: 'toString' on null

Please note, I have done the sqlite3.wasm update as require by the Amplify Library.
Any help is much appreciated.

**Comment by jobypthomas** [comment]
@salihgueler 
When added the .hasError for the future builder, I found the following:
<img width="636" alt="Screen Shot 2022-11-26 at 7 40 53 AM" src="https://user-images.githubusercontent.com/5605476/204089501-5be8286b-2514-4528-b42b-126a377a971d.png">

**Comment by salihgueler** [comment]
Hello @jobypthomas This happens only during the deployment right?

**Comment by jobypthomas** [comment]
Hi @salihgueler Yes, this happens only when testing the deployed app. When the app runs locally, it works just fine.

**Comment by jobypthomas** [comment]
Hello @salihgueler, There seems to be an open issue https://github.com/aws-amplify/amplify-flutter/issues/2330

**Comment by salihgueler** [comment]
I will let the team know about it. I will take care of the solution with a state management in two weeks.

**Comment by jobypthomas** [comment]
@salihgueler Thank you!

**Comment by abdallahshaban557** [comment]
@jobypthomas  - the fix has been identified on our end, and will it will be released soon! Please follow that GH issue for updates!

**Comment by jobypthomas** [comment]
@abdallahshaban557 This issue has been pending for a while. Do you have an update?

**Comment by abdallahshaban557** [comment]
@jobypthomas  - the issue has been fixed now - I realize you are aware now from your responses on the other issues in the Amplify Flutter repo.

**Comment by salihgueler** [comment]
Hello @jobypthomas I did a version of the cubit with lots of cleanup and theming. You can check it out with the default branch. Closing this issue for now for that.
