### ISSUE TITLE
branch with working solution

### ISSUE THREAD

**Issue by xpavlic4** [salihgueler/amplify_grocery_list#2]
Hi, 

could you publish the final solution on some a branch?

**Comment by salihgueler** [comment]
Hello @xpavlic4, thank you for your issue! I will push the branch with the solution after the re:invent. I will give you updates here.

**Comment by salihgueler** [comment]
Hello @xpavlic4 You can check the **finished** branch and a video here --> https://www.youtube.com/watch?v=SqyEhFbzlks for follow along.
